name: CI-coverage

on:
    push:
        tags:
            - '*.*.*'
jobs:
    test:
        runs-on: ${{ matrix.operating-system }}
        strategy:
            matrix:
                operating-system: [ ubuntu-latest ]
                php-versions: [ '8.3' ]
                php-unit-versions: [ '10.2' ]
                symfony-versions: ['7.0' ]
        name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }} - PHPUnit ${{ matrix.php-unit-versions }}
        steps:
            -   uses: actions/checkout@v4

            -   name: Cache Composer dependencies
                uses: actions/cache@v4
                with:
                    path: /tmp/composer-cache
                    key: ${{ runner.os }}-${{ matrix.symfony-versions }}-${{ hashFiles('**/composer.lock') }}

            -   name: composer
                uses: php-actions/composer@v6
                with:
                    php_version: ${{ matrix.php-versions }}
                    php_extensions: xdebug gd

            -   name: PHPUnit Tests
                uses: php-actions/phpunit@v3
                with:
                    version: ${{ matrix.php-unit-versions }}
                    php_version: ${{ matrix.php-versions }}
                    php_extensions: xdebug gd
                    bootstrap: vendor/autoload.php
                    configuration: phpunit.xml.dist
